### ISSUE TITLE
Tileset contamination bug

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#16]
![screen shot 2016-04-28 at 19 04 45](https://cloud.githubusercontent.com/assets/12588098/14896134/2b5dcbce-0d74-11e6-9acd-ded3678655f4.png)

Somehow icons are getting pulled out of different tilesets. Switching between tilesets or even sometimes just advancing the level seems to trigger this.

**Comment by Gantonator** [comment]
I cannot reproduce this bug on my machine no matter what I try.

**Comment by tpict** [comment]
i've reproduced this on two machines on OS X so i think they must be disagreeing with those icons you made. maybe they just got passed through when i tried to re-encode them

**Comment by tpict** [comment]
this doesn't happen in linux, but the performance really sucks on it

really need people to test this out, @userzjw if you have OS X on your macbook could you try running the game in that and see what happens?
