### ISSUE TITLE
Undo limit bugs

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#18]
currently the level editor only allows 20 undos unless you create a new level, in which case now both the game and level editor allow 100 undos. reminding myself to fix this

also asking for suggestions regarding a sensible upper limit for level editor undos. 100 feels a little small to me since it only takes a second to put 100 items down when you have drag-to-place (see #4)

**Comment by Gantonator** [comment]
Just make undo some crazy huge number for all scenarios.  I'm not sure why limit it anyway if not for technological reasons.  It adds nothing to gameplay because there is no penalty for resetting the level anyway.

**Comment by tpict** [comment]
the penalty is losing the 300 - 20 moves you couldn't undo

**Comment by Gantonator** [comment]
Forcing the player to manually re enter their solution if they make a mistake 21 moves back.  If someone playing the game for fun then the challenge isn't entering the commands but working out the solution.  Other sokoban clients have infinite undo.  Like Sokoban++.  I say make it infinite or lacking that 1000+

**Comment by tpict** [comment]
i agree with you but i'm pretty sure there's something in the requirements document about an undo limit that we'll have to address

**Comment by Gantonator** [comment]
I can't see anything about an undo limit.

**Comment by tpict** [comment]
@RosieBellini we ok just ditching FixedSizeStack and allowing infinite undos? it'll be less testing for you

**Comment by RosieBellini** [comment]
This all sounds great to us - the undo limit was simply installed as we thought they'd be a problem with the size of the stack but if you've resolved it we're cool with that.

**Comment by tpict** [comment]
if we ditch FixedSizeStack it's possible for the player to move back and forth until they fill up their RAM... i'm going to try removing it, then moving the player say 10000 times, and i'll see how much memory it uses up. if it's not filling gigabytes i suggest we just tell the player that they exceeded a move limit (of however many tens of thousands), otherwise stick with what we've got and have a limit of maybe 1000

**Comment by Gantonator** [comment]
I think the player would have to move until the heat death of the universe for that to be an issue.

**Comment by tpict** [comment]
i'm testing it right now

**Comment by tpict** [comment]
about 600MB for 20,000 moves. thoughts everyone?

**Comment by Gantonator** [comment]
Its fine but why not limit it to 2000 or something.  I don't think any sokoban levels take that many moves.  Maybe they do, there might be huge ones like there are giant crosswords.

**Comment by tpict** [comment]
well, we still haven't decided on a sensible limit for the game size, which plays a role in how we work this out. if they're not going to be playing huge maps then it seems improbable that they'll ever expend their RAM given that would take ~100k moves...

**Comment by tpict** [comment]
http://webmshare.com/0EVwd everyone watch this (important)

**Comment by tpict** [comment]
i can manage about 11 moves per second moving as fast as i can. i have 2 gigs of memory available. it would take me about 1 and 3/4 hours to fill up my RAM, moving as fast as i possibly can (and that's just back and forth between two spaces).

is this something we can just ignore?

**Comment by Gantonator** [comment]
That's assuming that it was ALL trying to solve one single level without resetting or undoing.  And constantly moving.

**Comment by Gantonator** [comment]
That is a good webm

**Comment by tpict** [comment]
exactly, plus my fingers were already tiring after 10 seconds, never mind 2 hours. shall i push my working copy?

**Comment by Gantonator** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0
