### ISSUE TITLE
Refactor class names

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#19]
need suggestions on sensible class names. these are the current names:

- BoxTerm: main class, handles menubar and associated operations (name from old Box Terminator title)
- SokobanGame: the main panel, handles key inputs and switching out panels when the game changes mode
- SpriteMap: imports icons and uses them to display a SokobanMap
- SaveState: representation of the game at a given "state" i.e. box, wall, goal, player positions, plus methods for moving these things around according to the game's rules
- SokobanMap: contains a stack of SaveStates and handles player interaction, e.g. moving around, figuring out which players are accessible, undo/redo
- Cell: a unit of the SpriteMap with a mouse listener

SingleThreadSolver, FixedSizeStack, SokobanObject and Coordinate are all fine imo

**Comment by Gantonator** [comment]
They should reference their superclass, like,  SokobanPanel, GamePanel, DisplayPanel, SpriteLabel.  Something like that.  SaveState could be MapState or something but it reads okay to me.

**Comment by tpict** [comment]
Those sound perfect!
