### ISSUE TITLE
Very laggy after cancelling solution of millions of pushes

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#25]
Try running the solver on a map that it struggles with, and once it's done ~1 million pushes, cancel it. It seems to take a long time to realise that you hit cancel and until it does the game runs so slowly you can get weird graphical bugs like player duplication.

**Comment by tpict** [comment]
@Gantonator

**Comment by Gantonator** [comment]
i think this just has to do with the jvm garbage collector.  There's nothing I can do without learning more complex memory management techniques.

**Comment by tpict** [comment]
the problem is that as time goes on it takes the solver more time to realise that you've cancelled the operation. once it notices and prints NO_SOLUTION the performance is fine again

**Comment by Gantonator** [comment]
OHhhhh.  I see I see.  That makes more sense.  You are right.
