### ISSUE TITLE
Multiple click-to-move operations can be run at once

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#26]
![screen shot 2016-04-30 at 21 47 24](https://cloud.githubusercontent.com/assets/12588098/14938527/23766424-0f1e-11e6-8c21-4c1c75dbb95d.png)
...and it does weird stuff!

i think a good solution for this will require a new class so i'm working on that now

**Comment by tpict** [comment]
i've changed my mind about that. nested classes aren't great, but to avoid them completely i'd need to make two new classes which just seems bad.

**Comment by Gantonator** [comment]
known shippable

**Comment by tpict** [comment]
i'm going to fix this tomorrow

**Comment by Gantonator** [comment]
Haha, sorry for closing this.  That was silly.
