### ISSUE TITLE
Suggestion: merge SokobanPanel and GamePanel, add SokobanMenu

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#30]
...yeah, i know, and i'm willing to do the work. the only reason Sokoban/GamePanel are separate at all at this point is because SokobanPanel is already at 700 lines. the menu bar makes up 300 of those lines though and the bulk of it is just the same 4 methods to add items to the menu bar. almost every operation in SokobanPanel needs a call to GamePanel so why not merge them together and move the menubar stuff out so it's readable?

**Comment by Gantonator** [comment]
I won't do any more stuff tonight if you want to do it but It is fine to have closely coupled modules.

**Comment by tpict** [comment]
i'm giving it a shot right now just to see how it looks

**Comment by tpict** [comment]
it didn't look good. at least with the current setup we have all the menu functionality in one class. i do wonder though how you would go about reorganising this program to be more readable, or if that's even possible in java
