### ISSUE TITLE
Program stuck when doing the print solution until the solution is done. Is there should be a function for users to shut down the thread when it takes too long? 

### ISSUE THREAD

**Issue by userzjw** [marcusjrc/lbuilder#5]

**Comment by Gantonator** [comment]
Yeah definitely, it will be put in a separate thread soon.  I am taking a break for a while now.

**Comment by userzjw** [comment]
public boolean solveLevel(){
    	long a=System.currentTimeMillis(); //Get current time when this method starts
        int currentStateIndex = 0;
        boolean solving = true;
        boolean solved = false;
        while (solving && currentStateIndex<seenStates.size()){
            map.loadSimpleState(seenStates.get(currentStateIndex));
            List<Coordinate[]> validPushes = validPushes(currentStateIndex);
            for (int i=0; i<validPushes.size();i++){
                boolean pushed = tryPush(currentStateIndex,validPushes.get(i));
                long b=System.currentTimeMillis(); //Get current time of each step
                if((b-a)/1000==10){     //If this method had run for 10 seconds send a confirmDialog if user choose no then end this method.
                int result = JOptionPane.showConfirmDialog(null, "Keep processing","Solution is processing",  JOptionPane.YES_NO_OPTION);
                switch (result) {
                case JOptionPane.YES_OPTION:
                	continue;
                case JOptionPane.NO_OPTION:
                	return false;                	
                case JOptionPane.CLOSED_OPTION:
                	return false;
                }
            }
                if(pushed){
                    solving=false;
                    solved=true;
                    break;
                }
                if(!solving){
                    break;
                }
            }
            currentStateIndex++;
        }
        return solved;
    }

**Comment by Gantonator** [comment]
Yo!!  That is a good solution!  I just saw this.  I have put it in a separate thread for now but this is also something to think about putting in.
