### ISSUE TITLE
Merge BigMerge with master

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#6]
i wanted to put this off until BigMerge contained all the functionality that Marcus' and Rosie's original level builder does. are we all happy to do so now?

(i think the sensible approach is to just copy master to a new branch and overwrite it with BigMerge)

**Comment by Gantonator** [comment]
Yes

**Comment by tpict** [comment]
i'll take care of it in a minute, just writing Crop function

**Comment by tpict** [comment]
Done!
