### ISSUE TITLE
About level editor, the increase Magnification can only increase the main frame 

### ISSUE THREAD

**Issue by userzjw** [marcusjrc/lbuilder#8]
![image](https://cloud.githubusercontent.com/assets/18551565/14868560/162eb4f6-0cc6-11e6-8150-91a99c9ea2ab.png)

**Comment by Gantonator** [comment]
It used to increase the size of the palette but I thought it looked weird.  We should decide what to do tomorrow.

**Comment by userzjw** [comment]
cool

**Comment by Gantonator** [comment]
I think we decided to leave it as it is... I think.
